import React, { useState } from 'react';
import { CreditsInfo, ForumThread, Poll } from '../types';
import { Plus, Trash2 } from 'lucide-react';

interface Props { polls: Poll[]; threads: ForumThread[]; credits: CreditsInfo; onAddPoll: (poll: Omit<Poll, 'id'>) => void; onDeletePoll: (id: string) => void; onDeleteThread: (id: string) => void; onSaveCredits: (credits: CreditsInfo) => void; }
const field = 'w-full bg-transparent border border-[#c4c6cd] rounded-[2px] px-3 py-2 text-sm';
export const AdminCommunity: React.FC<Props> = ({ polls, threads, credits, onAddPoll, onDeletePoll, onDeleteThread, onSaveCredits }) => {
  const [question, setQuestion] = useState(''); const [context, setContext] = useState(''); const [closes, setCloses] = useState(''); const [options, setOptions] = useState(''); const [creditForm, setCreditForm] = useState(credits); const [saved, setSaved] = useState(false);
  const submitPoll = (event: React.FormEvent) => { event.preventDefault(); const labels = options.split('\n').map((value) => value.trim()).filter(Boolean); if (labels.length < 2) return; onAddPoll({ question: question.trim(), context: context.trim(), closes: closes.trim(), options: labels.map((label, index) => ({ id: `option-${Date.now()}-${index}`, label, votes: 0 })) }); setQuestion(''); setContext(''); setCloses(''); setOptions(''); };
  return <main className="max-w-[1120px] mx-auto px-5 sm:px-8 md:px-12 py-8 md:py-12 w-full animate-in fade-in duration-300"><h1 className="font-serif text-3xl md:text-4xl font-bold text-[#041627]">Community & Page Manager</h1><p className="text-[#5e5e5b] text-sm mt-2 mb-10">Create and remove polls and forum threads, and update the public credits page.</p><div className="grid lg:grid-cols-2 gap-8">
    <section className="paper-card rounded-[4px] p-6"><h2 className="font-serif text-2xl font-semibold mb-5">Add a poll</h2><form onSubmit={submitPoll} className="space-y-3"><input required className={field} placeholder="Poll question" value={question} onChange={e => setQuestion(e.target.value)} /><input className={field} placeholder="Context (optional)" value={context} onChange={e => setContext(e.target.value)} /><input className={field} placeholder="Closing note (optional)" value={closes} onChange={e => setCloses(e.target.value)} /><textarea required rows={4} className={field} placeholder="One answer option per line (at least two)" value={options} onChange={e => setOptions(e.target.value)} /><button className="inline-flex items-center gap-2 bg-[#041627] text-white text-xs font-semibold uppercase tracking-widest px-4 py-3 rounded-[2px]"><Plus className="w-4 h-4" /> Create poll</button></form><h3 className="eyebrow mt-8 mb-3">Existing polls</h3><div className="space-y-2">{polls.map(poll => <div key={poll.id} className="flex items-start justify-between gap-3 border-t border-[#dedad1] py-3"><div><p className="font-medium text-sm">{poll.question}</p><p className="text-xs text-[#74777d]">{poll.options.length} options · {poll.options.reduce((n, option) => n + option.votes, 0)} votes</p></div><button aria-label={`Delete poll: ${poll.question}`} onClick={() => window.confirm('Delete this poll and its votes?') && onDeletePoll(poll.id)} className="text-red-700 p-1"><Trash2 className="w-4 h-4" /></button></div>)}</div></section>
    <section className="paper-card rounded-[4px] p-6"><h2 className="font-serif text-2xl font-semibold mb-5">Forum threads</h2>{threads.length ? <div className="space-y-2">{threads.map(thread => <div key={thread.id} className="flex items-start justify-between gap-3 border-t border-[#dedad1] py-3"><div><p className="font-medium text-sm">{thread.title}</p><p className="text-xs text-[#74777d]">{thread.category} · {thread.comments.length} replies</p></div><button aria-label={`Delete thread: ${thread.title}`} onClick={() => window.confirm('Delete this thread and all its replies?') && onDeleteThread(thread.id)} className="text-red-700 p-1"><Trash2 className="w-4 h-4" /></button></div>)}</div> : <p className="text-sm text-[#74777d]">No forum threads yet.</p>}</section>
    <section className="paper-card rounded-[4px] p-6 lg:col-span-2"><h2 className="font-serif text-2xl font-semibold mb-5">Credits page</h2><form className="grid sm:grid-cols-2 gap-4" onSubmit={event => { event.preventDefault(); onSaveCredits(creditForm); setSaved(true); setTimeout(() => setSaved(false), 2500); }}><label className="text-xs font-semibold uppercase tracking-wider">President<input className={`${field} mt-2`} value={creditForm.president} onChange={e => setCreditForm({ ...creditForm, president: e.target.value })} /></label><label className="text-xs font-semibold uppercase tracking-wider">Vice presidents<input className={`${field} mt-2`} value={creditForm.vicePresidents} onChange={e => setCreditForm({ ...creditForm, vicePresidents: e.target.value })} /></label><label className="text-xs font-semibold uppercase tracking-wider sm:col-span-2">Credits note<input className={`${field} mt-2`} value={creditForm.footer} onChange={e => setCreditForm({ ...creditForm, footer: e.target.value })} /></label><button className="bg-[#041627] text-white text-xs font-semibold uppercase tracking-widest px-5 py-3 rounded-[2px] w-fit">Save credits</button>{saved && <p role="status" className="text-sm text-emerald-700 self-center">Credits updated.</p>}</form></section>
    </div></main>;
};
