import React, { useState } from 'react';
import { BarChart3, Check, Trash2 } from 'lucide-react';
import { Poll } from '../types';

export const PollsView: React.FC<{ polls: Poll[]; onVote: (pollId: string, optionId: string) => void; isAdmin?: boolean; onDeletePoll?: (pollId: string) => void }> = ({ polls, onVote, isAdmin = false, onDeletePoll }) => {
  const [voted, setVoted] = useState<Record<string, string>>(() => JSON.parse(localStorage.getItem('pollVotes') || '{}'));
  const vote = (pollId: string, optionId: string) => { if (voted[pollId]) return; const next = { ...voted, [pollId]: optionId }; setVoted(next); localStorage.setItem('pollVotes', JSON.stringify(next)); onVote(pollId, optionId); };
  return <main className="flex-grow w-full max-w-[1120px] mx-auto px-5 sm:px-8 md:px-12 py-12 md:py-20 animate-in fade-in duration-300"><section className="max-w-3xl mb-12"><p className="eyebrow mb-4">The question is open</p><h1 className="font-serif text-4xl sm:text-5xl md:text-6xl font-bold text-[#041627] tracking-tight leading-[1.05]">Club Polls</h1><p className="text-base sm:text-lg text-[#44474c] leading-relaxed mt-6 max-w-2xl">Take a position, see where the room stands, and bring your reasoning to the next discussion.</p></section>{polls.length === 0 ? <p className="paper-card rounded-[4px] p-8 text-sm text-[#5e5e5b]">There are no active polls right now.</p> : <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">{polls.map((poll) => { const total = poll.options.reduce((sum, option) => sum + option.votes, 0); const hasVoted = Boolean(voted[poll.id]); return <article key={poll.id} className="paper-card p-6 sm:p-8 rounded-[4px]"><div className="flex items-center justify-between gap-3 mb-5"><span className="eyebrow">{poll.context}</span><div className="flex items-center gap-3"><BarChart3 className="w-5 h-5 text-[#ba5a3a]" strokeWidth={1.5} />{isAdmin && onDeletePoll && <button type="button" onClick={() => window.confirm('Delete this poll and its votes?') && onDeletePoll(poll.id)} className="inline-flex items-center gap-1 text-xs text-red-700 hover:text-red-900" aria-label={`Delete poll: ${poll.question}`}><Trash2 className="w-4 h-4" /> Delete</button>}</div></div><h2 className="font-serif text-2xl sm:text-3xl font-semibold text-[#041627] leading-snug">{poll.question}</h2><div className="space-y-3 mt-7">{poll.options.map((option) => { const percentage = total ? Math.round((option.votes / total) * 100) : 0; return <button key={option.id} onClick={() => vote(poll.id, option.id)} disabled={hasVoted} className="w-full text-left group disabled:cursor-default"><div className="flex justify-between gap-3 text-sm mb-1.5"><span className={voted[poll.id] === option.id ? 'font-semibold' : ''}>{voted[poll.id] === option.id && <Check className="inline w-3.5 h-3.5 mr-1 text-[#ba5a3a]" />}{option.label}</span>{hasVoted && <span className="text-xs text-[#74777d]">{percentage}%</span>}</div><div className="h-2 bg-[#ece4d6] overflow-hidden rounded-full"><div className={`h-full transition-all duration-500 ${voted[poll.id] === option.id ? 'bg-[#ba5a3a]' : 'bg-[#173b4d] group-hover:bg-[#ba5a3a]'}`} style={{ width: hasVoted ? `${percentage}%` : '0%' }} /></div></button>; })}</div><div className="flex justify-between mt-7 pt-4 border-t border-[#dedad1] text-xs text-[#74777d]"><span>{hasVoted ? `${total} total responses` : 'Choose one response'}</span><span>{poll.closes}</span></div></article>; })}</div>}</main>;
};
